#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-
'''call for special agent function'''

# License: GNU General Public License v2

import sys

from cmk_addons.plugins.dell.special_agents.agent_dell_powerstore import main

if __name__ == "__main__":
    sys.exit(main())
